packages:
  - apps/*
  - packages/*

supportedArchitectures:
  cpu:
    - arm64
    - x64

allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": true
  "@google/genai": false
  electron: true
  electron-winstaller: false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
