packages:
  - apps/*
  - packages/*

supportedArchitectures:
  cpu:
    - arm64
    - x64

allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": true
  "@google/genai": false
  electron: true
  electron-winstaller: false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true

patchedDependencies:
  "@deepseek-ai/dsh-client-ui-conversation@0.1.0-rc.6": patches/@deepseek-ai__dsh-client-ui-conversation@0.1.0-rc.6.patch
  "@deepseek-ai/dsh-client-ui-sidebar@0.1.0-rc.6": patches/@deepseek-ai__dsh-client-ui-sidebar@0.1.0-rc.6.patch
